### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by AlphaNAlfonso69** [fioprotocol/fio-devhub#151]
Question on: https://github.com/fioprotocol/fio-devhub/tree/master/_docs/integration-guide/index.md

**Comment by AlphaNAlfonso69** [comment]
Why is it that we need to have another Wallet Address ,like FIO The Foundation for Interwallet Operability?It looks complicated and  takes some hours of operations of each transaction!How can we shorten this agony!?For this is not really a guaranteed help for Me,as a Bitcoin Awardee,I am not still a user,but a trying hard!I need some professional Help,for this conflicts with Public Agony with Bank terrorism.How can we solve this type of problem for it looks like it Rampants the Situation and Condition of Banking Problems and Conflicts!

**Comment by ericbutz** [comment]
Questions here are for devhub. Closing.
